service: backend

frameworkVersion: '4'
useDotenv: true

provider:
  name: aws
  runtime: python3.13
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'development'}
  logRetentionInDays: 30
  environment:
    APP_ENVIRONMENT: ${self:provider.stage}

functions:
  API:
    handler: src.main.handle
    timeout: 10
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: ${env:ALLOWED_ORIGINS}
            maxAge: 60
  # cron:
  #   handler: src.scraper.run
  #   events:
  #       - schedule: cron(10 03 * * ? *) #run at 03:10 (UTC) every day.


custom:
  pythonRequirements:
    usePoetry: true
    noDeploy:
      - boto3
      - botocore

plugins:
  - serverless-python-requirements